version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpwrcbrbwqisfmxhopmd
    ports:
      - "5432:5432"
    volumes:
      - ./persistence/postgres:/var/lib/postgresql/data

#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
