version: '3.8'

services:
  postgres:
    image: postgres
    container_name: gpwrcbrbwqisfmxhopmd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpwrcbrbwqisfmxhopmd
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: gpwrcbrbwqisfmxhopmd-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongoroot
      MONGO_INITDB_DATABASE: gpwrcbrbwqisfmxhopmd
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./config/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js

volumes:
  pg:
  mongo:
